BuLiTippBoot/BuLiTippBoot/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'BuLiTippApp.views.home', name='home'),
    # url(r'^BuLiTipp/', include('BuLiTipp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', "django.contrib.auth.views.login"),
    url(r'^register/', "BuLiTippApp.views.register"),
    url(r'^logout/', "BuLiTippApp.views.logout"),

    # Account management
    url(r'^account/$', "BuLiTippApp.views.account"),
    url(r'^account/delete/$', "BuLiTippApp.views.delete_account"),
    
    # Change password functionality
    url(r'^pwchange/', "django.contrib.auth.views.password_change"),
    url(r'^pwchangedone/', "django.contrib.auth.views.password_change_done"),

    url(r'^BuLiTipp/$', 'BuLiTippApp.views.index'),
    url(r'^BuLiTipp/(?P<spielzeit_id>\d+)/$', 'BuLiTippApp.views.index'),
    url(r'^BuLiTipp/news/$', 'BuLiTippApp.views.news'),
    url(r'^BuLiTipp/start/(?P<spielzeit_id>\d+)/$', 'BuLiTippApp.views.start'),
    url(r'^BuLiTipp/about/$', 'BuLiTippApp.views.about'),
    url(r'^BuLiTipp/basic/$', 'BuLiTippApp.views.basic'),
    url(r'^BuLiTipp/kommi/$', 'BuLiTippApp.views.post_kommentar'),
    url(r'^BuLiTipp/kommi/delete/$', 'BuLiTippApp.views.delete_kommentar'),
    url(r'^BuLiTipp/best/$', 'BuLiTippApp.views.best'),
    url(r'^BuLiTipp/sp(?P<spieltag_id>\d+)/$', 'BuLiTippApp.views.detail'),
    url(r'^BuLiTipp/sp(?P<spieltag_id>\d+)/tipp/$', 'BuLiTippApp.views.tippen'),
    url(r'^BuLiTipp/stat/user/(?P<spielzeit_id>\d+)/$', 'BuLiTippApp.views.user_site'),
    url(r'^BuLiTipp/stat/user/$', 'BuLiTippApp.views.user_site'),

    url(r'^BuLiTipp/saisontipp/(?P<spielzeit_id>\d+)/$', 'BuLiTippApp.views.saisontipp'),
    url(r'^BuLiTipp/saisontipp/$', 'BuLiTippApp.views.saisontipp'),

    url(r'^BuLiTipp/spielzeit/$', 'BuLiTippApp.views.spielzeit'),
    url(r'^BuLiTipp/spielzeit/(?P<spielzeit_id>\d+)/$', 'BuLiTippApp.views.spielzeit'),

    url(r'^BuLiTipp/verein/(?P<verein_id>\d+)/$', 'BuLiTippApp.views.verein'),

    url(r'^BuLiTipp/spieltag/(?P<spieltag_id>\d+)/(?P<spielzeit_id>\d+)/$', 'BuLiTippApp.views.detail'),
    url(r'^BuLiTipp/test/(?P<spieltag_id>\d+)/(?P<spielzeit_id>\d+)/$', 'BuLiTippApp.views.detail'),
    url(r'^BuLiTipp/test/$', 'BuLiTippApp.views.test'),
)

BuLiTippBoot/BuLiTippApp/models/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from punkterechner import Punkterechner
# Create your models here.

class News(models.Model):
	class Meta:
		app_label = 'BuLiTippApp'
	author = models.ForeignKey(User)
	datum = models.DateTimeField()
	text = models.CharField(max_length=1000)
	
class Spielzeit(models.Model):
	class Meta:
		app_label = 'BuLiTippApp'
	bezeichner = models.CharField(max_length=50)
	saisontipp_end = models.DateTimeField(null=True)
	def __init__(self, *args, **kwargs):
		super(Spielzeit, self).__init__(*args, **kwargs)
	def __unicode__(self):
		return self.bezeichner
	def save(self):
		first=False
		if self.id is None: first=True
		super(Spielzeit, self).save()
		if first is True:
			for i in range(1, 35):
				s = Spieltag()
				s.spielzeit_id = self.id
				s.nummer = i
				s.datum = timezone.now()
				s.save()
	def next_spieltag(self):
		''' Gibt den naechsten Spieltag, anhand Datum, zurueck.
		    Wenn kein naechster Spieltag, wird der letzte Spieltag zurueck gegeben.
		'''
		now = timezone.now()
		try:
			return self.spieltag_set.filter(datum__gte=now)[0]
		except:
			return self.spieltag_set.all().order_by("nummer").reverse()[0]
	def userpunkteplatz(self):
		return Bestenliste().spielzeit(self.id)
	def is_tippable(self):
		return timezone.now()<self.saisontipp_end
	
class Spieltag(models.Model):
	class Meta:
		app_label = 'BuLiTippApp'
	spielzeit = models.ForeignKey(Spielzeit)
	datum = models.DateTimeField()
	nummer = models.IntegerField()
	admin_order_field = "nummer"
#	def __init__(self, *args, **kwargs):
#		super(Spieltag, self).__init__(*args, **kwargs)
		#self.spielzeit=spielzeit
		#self.datum=datum
		#self.nummer=nummer
	def __unicode__(self):
		return "%d/%s" % (self.nummer, self.spielzeit)
	def is_tippable(self):
		return timezone.now()<self.datum
	def next(self):
		if self.nummer>=34:
			return None
		try:
			return Spieltag.objects.filter(spielzeit_id=self.spielzeit.id).filter(nummer=self.nummer+1)[0]
		except:
			return None
	def previous(self):
		if self.nummer<=1:
			return None
		try:
			return Spieltag.objects.filter(spielzeit_id=self.spielzeit.id).filter(nummer=self.nummer-1)[0]
		except:
			return None
	#returns [(spiel, tipp, punkte)] for this Spieltag for a certain user
	def spieltipp(self, user_id, fremd_tipps=True):
		tipps = Tipp.objects.filter(spiel_id__spieltag_id=self.id).filter(user_id=user_id)
		tipps = {t.spiel_id: t for t in tipps}
		punkte = {t.spiel_id: t.punkte() for t in tipps.values() }
		fremdtipps={}
		if fremd_tipps:
			if not self.is_tippable():
				for spiel in self.spiel_set.all():
					ftipps= spiel.tipps()
					ftipps= ftipps.exclude(user_id=user_id)
					fremdtipps[spiel.id] = [(t.user.username, t.ergebniss, t.punkte()) for t in ftipps]
		return [(spiel, tipps[spiel.id] if spiel.id in tipps.keys() else None, punkte[spiel.id] if spiel.id in punkte.keys() else None, fremdtipps[spiel.id] if spiel.id in fremdtipps.keys() else None) for spiel in self.spiel_set.all()]
	def userpunkteplatz(self):
		return Bestenliste().spieltag(self.id)

class Bestenliste():
	class Meta:
		app_label = 'BuLiTippApp'
	def all(self, user_id=-1, full=True):
		return self.query(user_id=user_id, full=full)
	def spieltag(self, spieltag_id, user_id=-1, full=True):
		return self.query(spieltag_id=spieltag_id, user_id=user_id, full=full)
	def spielzeit(self, spielzeit_id, user_id=-1, full=True):
		return self.query(spielzeit_id=spielzeit_id, user_id=user_id, full=full)
	def query(self, user_id=-1, full=True, spieltag_id=None, spielzeit_id=None):
		userpunkte=[]
		#fuer jeden user
		for user in User.objects.all():
			#ermittle alle tipps
			tipps = Tipp.objects.filter(user_id=user.id)
			if spieltag_id is not None:
				tipps=tipps.filter(spiel_id__spieltag_id=spieltag_id)
			if spielzeit_id is not None:
				tipps=tipps.filter(spiel_id__spieltag_id__spielzeit_id=spielzeit_id)
			#summiere die punkte der Tipps
			punkte = sum(map(lambda tipp: 0 if tipp.punkte() is None else tipp.punkte(), tipps))
			userpunkte.append((user, punkte))
		userpunkte.sort(key=lambda punkt:punkt[1], reverse=True)
		userpunkteplatz=[(userpunkt[0], userpunkt[1], platz+1) for platz, userpunkt in enumerate(userpunkte)]
		for i, userp in enumerate(userpunkte):
			if user_id == userp[0].id:
				platz=i
				break
		first=True
		j=0
		if not full:
			for i, userp in enumerate(userpunkteplatz[:]):
				if i < 3 or platz -2 < i < platz + 2:
					j+=1
					first=True
					continue
				if first:
					first=False
					userpunkteplatz[i]=("...", "...", "...")
					j+=1
				else:
					del userpunkteplatz[j]
		return userpunkteplatz

class Verein(models.Model):
	class Meta:
		app_label = 'BuLiTippApp'
	name = models.CharField(max_length=75)
	abk = models.CharField(max_length=5,default='')
	def __unicode__(self):
		return unicode(self.name)

class Spiel(models.Model):
	class Meta:
		app_label = 'BuLiTippApp'
	heimmannschaft = models.ForeignKey(Verein, related_name="heimmannschaft")
	auswaertsmannschaft = models.ForeignKey(Verein, related_name="auswaertsmannschaft")
	spieltag = models.ForeignKey(Spieltag)
	ergebniss = models.CharField(max_length=5)
	datum = models.DateTimeField(null=True)
	def __unicode__(self):
		return "%s vs %s" % (unicode(self.heimmannschaft), unicode(self.auswaertsmannschaft))
	def tipps(self):
		return self.tipp_set.all()
	def is_tippable(self):
		if (self.datum is not None):
			return timezone.now()<self.datum
		if (self.spieltag is not None):
			return self.spieltag.is_tippable()
		return False


class Tipp(models.Model):
	class Meta:
		app_label = 'BuLiTippApp'
	user = models.ForeignKey(User)
	spiel = models.ForeignKey(Spiel)
	def ergebniss_h(self):
		e=str(self.ergebniss)
		if ":" in e:
			return e.split(":")[0]
		return None
	def ergebniss_a(self):
		e=str(self.ergebniss)
		if ":" in e:
			return e.split(":")[1]
		return None
	ergebniss = models.CharField(max_length=5)
	def __unicode__(self):
		s = "%s: %s (%s)" % (self.id, self.ergebniss, self.user_id)
		return unicode(s)
	def punkte(self):
		return Punkterechner().punkte(self)
	
class Kommentar(models.Model):
	class Meta:
		app_label = 'BuLiTippApp'
	datum = models.DateTimeField()
	text = models.CharField(max_length=500)
	user = models.ForeignKey(User)
	reply_to = models.ForeignKey('self', null=True)
	spieltag = models.ForeignKey(Spieltag, null=True)

############################################################################
###   saisonale Tipps   ###
############################################################################

class Meistertipp(models.Model):
	class Meta:
		app_label = 'BuLiTippApp'
		unique_together = ("user", "spielzeit")
	datum = models.DateTimeField(auto_now=True)
	user = models.ForeignKey(User)
	mannschaft = models.ForeignKey(Verein)
	spielzeit = models.ForeignKey(Spielzeit)
	def __unicode__(self):
		s = "%s: %s (%s)" % (self.user, unicode(self.mannschaft), self.spielzeit)
		return unicode(s)

class Herbstmeistertipp(models.Model):
	class Meta:
		app_label = 'BuLiTippApp'
		unique_together = ("user", "spielzeit")
	datum = models.DateTimeField(auto_now=True)
	user = models.ForeignKey(User)
	mannschaft = models.ForeignKey(Verein)
	spielzeit = models.ForeignKey(Spielzeit)
	def __unicode__(self):
		s = "%s: %s (%s)" % (self.user, unicode(self.mannschaft), self.spielzeit)
		return unicode(s)

class Absteiger(models.Model):
	class Meta:
		app_label = 'BuLiTippApp'
		unique_together = ("user", "spielzeit", "mannschaft")
	datum = models.DateTimeField(auto_now=True)
	user = models.ForeignKey(User)
	mannschaft = models.ForeignKey(Verein)
	spielzeit = models.ForeignKey(Spielzeit)
	ABSTEIGER_ANZAHL = 3
	def __unicode__(self):
		s = "%s: %s (%s)" % (self.user, unicode(self.mannschaft), self.spielzeit)
		return unicode(s)
	def save(self):
		count = 0
		try:
			count = len(Absteiger.objects.filter(user_id=self.user.id, spielzeit_id=self.spielzeit.id))
		except:
			pass
		if count>=self.ABSTEIGER_ANZAHL:
			raise Exception("no more than " + str(self.ABSTEIGER_ANZAHL)  + " Absteiger allowed")
		return super(Absteiger, self).save()

BuLiTippBoot/BuLiTippApp/models/models_statistics.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from punkterechner import Punkterechner
from models import Spielzeit, Verein

# Create your models here.

class Tabelle(models.Model):
	class Meta:
		app_label = 'BuLiTippApp'
	spielzeit = models.ForeignKey(Spielzeit)
	platz = models.IntegerField()
	mannschaft = models.ForeignKey(Verein)
	punkte = models.IntegerField()
	def __unicode__(self):
		return "%s: %s(%s)" % (str(self.platz), unicode(self.mannschaft), str(self.punkte))
	def getMannschaftPlatz(self, spielzeit):
		if (spielzeit is not None):
			sid = spielzeit.id
		else:
			sid = None
		if (sid is None):
			return {t.mannschaft.id: t.platz for t in Tabelle.objects.all()}
		else:
			return {t.mannschaft.id: t.platz for t in Tabelle.objects.filter(spielzeit_id=sid)}
	def refresh(self):
		Tabelle.objects.all().delete()
		pr = Punkterechner()
		#fuer jede spielzeit:
		for sz in Spielzeit.objects.all():
			#fuer jedes abgelaufene spiel:
			mannschaft_punkte_tore={}
			for st in sz.spieltag_set.all():
				for s in st.spiel_set.all():
					#ermittlke punkte und schreibe sie den vereinen gut
					m1 = s.heimmannschaft.id
					m2 = s.auswaertsmannschaft.id
					if (m1 in mannschaft_punkte_tore.keys()):
						alt1 = mannschaft_punkte_tore[m1][0]
						tor1 = mannschaft_punkte_tore[m1][1]
					else:
						alt1 = 0
						tor1 = 0
					if (m2 in mannschaft_punkte_tore.keys()):
						alt2 = mannschaft_punkte_tore[m2][0]
						tor2 = mannschaft_punkte_tore[m2][1]
					else:
						alt2 = 0
						tor2 = 0
					try:
						toto = pr.toto(s.ergebniss)
					except:
						continue
					if (toto == 1):
						p1=3
						p2=0						
					elif (toto == 2):
						p1=0
						p2=3
					elif (toto == 0):
						p1=1
						p2=1
					diff = pr.diff(s.ergebniss)
					mannschaft_punkte_tore[m1]=[alt1 + p1, tor1-diff]
					mannschaft_punkte_tore[m2]=[alt2 + p2, tor2+diff]
			mannschaft_punkte_tore = sorted(mannschaft_punkte_tore.iteritems(), key=lambda (k, v): (-v[0]*1000-v[1], k) )
			for (i, v) in enumerate(mannschaft_punkte_tore):
				t=Tabelle()
				t.spielzeit = sz
				t.platz = i+1
				#print v
				t.mannschaft_id = v[0]
				t.punkte = v[1][0]
				t.save()

BuLiTippBoot/BuLiTippApp/models/punkterechner.py
import models

class Punkterechner():
	'''Der Standard-Punkterecher: 3 Punkte fuer korrektes Ergebnis, 2 fuer Differenz, 1 fuer tendenz.
	'''
	def differenz(self, erg1, erg2):
		assert ":" in erg1
		assert ":" in erg2
		assert len(erg1.split(":"))==2
		assert len(erg2.split(":"))==2
		heim=int(erg1.split(":")[0])
		ausw=int(erg1.split(":")[1])
		erg1diff=heim-ausw
		heim=int(erg2.split(":")[0])
		ausw=int(erg2.split(":")[1])
		erg2diff=heim-ausw
		return erg1diff==erg2diff


	def tendenz(self, erg1, erg2):
		if self.toto(erg1)==self.toto(erg2):
			return True
		else:
			return False
	def toto(self, erg):
		assert ":" in erg
		assert len(erg.split(":"))==2
		heim=int(erg.split(":")[0])
		ausw=int(erg.split(":")[1])
		if heim==ausw:
			return 0
		elif heim>ausw:
			return 1
		else:
			return 2
	def diff(self, erg):
		assert ":" in erg
		assert len(erg.split(":"))==2
		heim=int(erg.split(":")[0])
		ausw=int(erg.split(":")[1])
		return ausw-heim
	def punkte(self, tipp):
		try:
			spiel = tipp.spiel
			if spiel.ergebniss == tipp.ergebniss:
				return 3
			elif self.differenz(spiel.ergebniss, tipp.ergebniss):
				return 2
			elif self.tendenz(spiel.ergebniss, tipp.ergebniss):
				return 1
			else:
				return 0
		except:
			return None

BuLiTippBoot/BuLiTippApp/templates/about.html
{% extends "base_site.html" %}
{% load i18n  %}
{% block breadcrumbs %}
    <div class="breadcrumbs">
    	<div style="float:left">
		    <a href="{% url BuLiTippApp.views.index %}">{% trans 'Home' %}</a>
		    {% if title %} &rsaquo; {{ title }}{% endif %}
		    
			-&rsaquo;
			<a href="{% url BuLiTippApp.views.news %}">Mitteilungen</a>
		    
	    </div>
    	<div style="float:right;">
    		{% include "navigation.html" %}
    	</div>
    	<div style="clear:both"></div>
    </div>
{% endblock %}

{% block content %}
<h1>About</h1>
{% endblock %}

BuLiTippBoot/BuLiTippApp/templates/add_form.html
{% extends "change_form.html" %}
{% load i18n %}

{% block form_top %}
  {% if not is_popup %}
    <p>{% trans "First, enter a username and password. Then, you'll be able to edit more user options." %}</p>
  {% else %}
    <p>{% trans "Enter a username and password." %}</p>
  {% endif %}
{% endblock %}

{% block after_field_sets %}
<script type="text/javascript">document.getElementById("id_username").focus();</script>
{% endblock %}

BuLiTippBoot/BuLiTippApp/templates/base_site.html
{% extends "basic.html" %}
{% load i18n %}

{% block title %}{{ title }}BuLiTipp - Bundesliga-Tipp Seite {% endblock %}

{% block branding %}
BuLiTipp
{% endblock %}

{% block nav-global %}{% endblock %}

BuLiTippBoot/BuLiTippApp/templates/basis.html
<!DOCTYPE html>
{% load bootstrap_toolkit %}
{% load url from future %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    {% bootstrap_stylesheet_tag %}
    {% bootstrap_stylesheet_tag "responsive" %}
    <style type="text/css">
        body {
            padding-top: 60px;
        }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    {% if LANGUAGE_BIDI %}
    {% endif %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.js"></script>
    {% bootstrap_javascript_tag %}
    {% block extra_head %}{% endblock %}
    {% block extrahead %}{% endblock %}
    {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div id="container" >
    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>

        <div id="user-tools">
            {% trans 'Welcome,' %}
        {% if user.is_active %}
            <strong><a href="{% url 'BuLiTippApp.views.account' %}">{% filter force_escape %}{% firstof user.first_name user.username %}{% endfilter %}</a></strong>.
            {% block userlinks %}
                {% url 'django-admindocs-docroot' as docsroot %}
                {% if docsroot %}
                    <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                {% endif %}
                <!--a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a--> /
                <a href="{% url 'BuLiTippApp.views.logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
    	{% else %}
                <a href="{% url 'django.contrib.auth.views.login' %}">{% trans 'Log in' %}</a> oder
                <a href="{% url 'BuLiTippApp.views.register' %}">{% trans 'Register' %}</a>
        {% endif %}
        </div>
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'BuLiTippApp.views.index' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    {% bootstrap_messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
		{% if message != None %}
			<div class="message">	{{ message }}	</div>
		{% endif %}
		{% if error != None %}
			<div class="error">	{{ error }}	</div>
		{% endif %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

BuLiTippBoot/BuLiTippApp/templates/contact.html
{% extends "base_site.html" %}
{% load i18n  %}
{% block breadcrumbs %}
    <div class="breadcrumbs">
    	<div style="float:left">
		    <a href="{% url BuLiTippApp.views.index %}">{% trans 'Home' %}</a>
		    {% if title %} &rsaquo; {{ title }}{% endif %}
		    
			-&rsaquo;
			<a href="{% url BuLiTippApp.views.news %}">Mitteilungen</a>
		    
	    </div>
    	<div style="float:right;">
    		{% include "navigation.html" %}
    	</div>
    	<div style="clear:both"></div>
    </div>
{% endblock %}

{% block content %}
<h1>Contact</h1>
{% endblock %}

BuLiTippBoot/BuLiTippApp/templates/navigation.html
<a href="{% url BuLiTippApp.views.saisontipp %}">Saisontipp</a>
|
<a href="{% url BuLiTippApp.views.user_site %}">Statistiken</a>

BuLiTippBoot/BuLiTippApp/templates/start.html
{% extends "base_site.html" %}

<!-- benötigte Variablen: spielzeiten, spieltipp_previous, spieltipp_next -->
{% load i18n  %}
{% block breadcrumbs %}

    <div class="breadcrumbs">
    	<div style="float:left">
		    <a href="{% url BuLiTippApp.views.index %}">{% trans 'Home' %}</a>
		    {% if title %} &rsaquo; {{ title }}{% endif %}
		    {% if aktuelle_spielzeit.id %}
			    -&rsaquo;
			    <a href="{% url BuLiTippApp.views.index aktuelle_spielzeit.id %}">{{ aktuelle_spielzeit.bezeichner }}</a>
		    {% endif %}
	    </div>
    	<div style="float:right;">
    		{% include "navigation.html" %}
    	</div>
    	<div style="clear:both"></div>
    </div>

{% endblock %}

{% block content %}
<div class="panel-group panel-info" id="accordion">
    <div class="panel-heading">Neueste Mitteilungen
        <a href="{% url BuLiTippApp.views.news %}" class="hright">alle Mitteilungen</a>
    </div>
    <div class="panel panel-default">
{% for news_ in news %}
        <div class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{news_.id}}">
                <strong>{{ news_.author.username }}</strong> schrieb am {{news_.datum}}
            </a>
        </div>
        <div id="collapse{{news_.id}}" class="panel-collapse collapse ">
            <div class="panel-body">
                {{news_.text|safe}}
            </div>
        </div>
{% endfor %}
    </div>
</div>

<!-- Wenn mehrere Saisons vorhanden -> Saison auswählen -->
{% if user.is_authenticated %}
    {% if spielzeiten|length > 1 %}
	    <h2>Bitte Spielzeit auswählen({{spielzeiten|length}}):</h2>
		    <ul>
		    {% for spielzeit in spielzeiten %}
			    <li><a href="{% url BuLiTippApp.views.index spielzeit.id %}">{{spielzeit.bezeichner}} auswählen</a></li>
		    {% endfor %}
		    </ul>
    {% endif %}
{% endif %}

{% if spielzeiten|length == 0 %}
	{% if spieltipp_previous %}
        <!-- Nav tabs -->
        <ul class="nav nav-tabs">
          <li><a href="#last" data-toggle="tab">Tabelle</a></li>
          <li><a href="#next" data-toggle="tab">Tippen</a></li>
          <li><a href="#season" data-toggle="tab">Saisonverlauf</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content pull-left">
            <div class="tab-pane" id="last">
		        {% with spieltag=spieltipp_previous.0.0.spieltag _no_navigation_="true" spieltipp=spieltipp_previous kommentare=spieltipp_previous.0.0.spieltag.kommentar_set.all %}
                <div class="panel panel-default">
	                <div class="panel-heading">Hier die Übersicht des {{spieltag.nummer}}. Spieltages!</div>
                    <div class="panel-body">
    			        {% include "spieltag/inline.html" %}
                    </div>
                </div>
	        </div>
            <div class="tab-pane" id="next">
	        {% if spieltipp_next %}
                <div class="panel panel-default">
                    <div class="panel-heading">Hier der nächste Spieltag!</div>
                    <div class="panel-body">
		            {% with spieltag=spieltipp_next.0.0.spieltag no_navigation="true" spieltipp=spieltipp_next  %}
		                Tippen noch möglich bis zum <strong>{{spieltag.datum}}</strong>!
		                {% include "spieltag/inline.html" %}
                        <p>
		                {% with kommentare=spieltag.kommentar_set.all %}
			                {% include "kommentar/detail.html" %}
		                {% endwith %}
                        </p>
		            {% endwith %}
                    </div>
                </div>
	        {% endif %}
            </div>
            <div class="tab-pane" id="season">
	        {% if not spieltag.is_tippable %}
		        {% with userpunkteplatz=aktuelle_spielzeit.userpunkteplatz spielzeit=aktuelle_spielzeit %}
			        <div class="panel panel-default" >
                        <div class="panel-heading">Saisonverlauf</div>
                        <div class="panel-body">
	    			        {% include "bestenliste/inline_nav.html" %}<!-- maybe _switchable ? -->
                        </div>
			        </div>
		        {% endwith %}
	        {% endif %}
            </div>
            <div class="clearfix">
		        {% include "kommentar/detail.html" %}
            </div>
        </div>

		{% endwith %}

	{% endif %}

{% endif %}

{% endblock %}